FROM willck/mistress:base

MAINTAINER Will Childs-Klein <will.childsklein@gmail.com>



# install dependencies and a few tools
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python \
    python-pip \
    curl \
    git

# fine ALL the bins
ENV PATH /usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin

# install code
#WORKDIR /mistress-mapreduce
CMD python /mistress-mapreduce/setup.py install
