FROM ubuntu

MAINTAINER Will Childs-Klein <will.childsklein@gmail.com>

# install dependencies and a few tools
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python \
    python-pip \
    curl \
    git

# find ALL the bins
ENV PATH /usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin

# install code
CMD python /mistress-mapreduce/setup.py install \
    scripts/generate_input_paths.sh
